# Workflow - mvn verify for All
name: verify-workflow

on:
  workflow_dispatch:
  workflow_call:

jobs:
  call-verify:
    uses: extact-io/msa-rms-parent/.github/workflows/verify-app-job.yml@main
    with:
      repo: ${{ github.repository }}
